### PR TITLE
Initial implementation of Nim-lang

### PR DESCRIPTION
**Pull request by Uniminin**
This merge request adds support for **experimental** Nim-lang

Relevant: Nim supports the following compilers https://github.com/nim-lang/Nim/blob/devel/compiler/extccomp.nim#L66 -> Tests required

Relevant: full list of Nim compilers can be found there https://github.com/nim-lang/Nim/blob/devel/compiler/extccomp.nim#L66

`--cc:clang` can be used to enforce compiler

Notice: Current CI on github is not efficient enough to implement all the logic that is required for this language (https://github.com/RXT0112/Zernit/pull/101#issuecomment-613498427) -> Needs to be implemented as custom script

## SECURITY
Quoting Nim support:
> Well you can use valgrind with Nim, yes. Usually Nim is safe unless you do FFI or low level stuff like raw pointers and manual memory allocation
> There's no null safety by default though

Relevant: https://github.com/nim-lang/RFCs/issues/4

### TODO:
- [ ] CPP contrib moved to separate merge request (@Uniminin )
- [X] Nim CI
  - [X] Add label
  - [X] Add Linting test
  - [X] Add label-pr
  - [ ] Custom script implemented (@Kreyren )
  - [ ] Implement checklist notice with a bot
- [ ] Build
  - [ ] compiler gcc
  - [ ] compiler nintendoSwitchGCC
  - [ ] compiler llvmGcc
  - [ ] compiler clang
  - [ ] compiler zig
  - [ ] compiler vcc
  - [ ] compiler clangcl
  - [ ] compiler icl
  - [ ] compiler icc
  - [ ] compiler lcc
  - [ ] compiler bcc
  - [ ] compiler dmc
  - [ ] compiler wcc
  - [ ] compiler tcc
  - [ ] compiler pcc
  - [ ] compiler ucc
- [ ] Check
  - [ ] compiler gcc
  - [ ] compiler nintendoSwitchGCC
  - [ ] compiler llvmGcc
  - [ ] compiler clang
  - [ ] compiler zig
  - [ ] compiler vcc
  - [ ] compiler clangcl
  - [ ] compiler icl
  - [ ] compiler icc
  - [ ] compiler lcc
  - [ ] compiler bcc
  - [ ] compiler dmc
  - [ ] compiler wcc
  - [ ] compiler tcc
  - [ ] compiler pcc
  - [ ] compiler ucc
- [ ] Nim documentation
  - [ ] What is nim?
  - [ ] Update CONTRIBUTING.md
- [ ] Nim Security
  - [ ] Add Valgrind
    - [ ] compiler gcc
    - [ ] compiler nintendoSwitchGCC
    - [ ] compiler llvmGcc
    - [ ] compiler clang
    - [ ] compiler zig
    - [ ] compiler vcc
    - [ ] compiler clangcl
    - [ ] compiler icl
    - [ ] compiler icc
    - [ ] compiler lcc
    - [ ] compiler bcc
    - [ ] compiler dmc
    - [ ] compiler wcc
    - [ ] compiler tcc
    - [ ] compiler pcc
    - [ ] compiler ucc

---

There are a number of other dependencies that you may need to install in order to use Nim. They Include:
* C Compiler. Either gcc or clang
* PCRE
* OpenSSL

### CODE REVIEW

**Comment by Kreyren** [comment]
@MikeRogers0 FWIW TypoCI also triggers on user names which is unexpected here.

image

**Comment by Kreyren** [comment]
@Uniminin We also need a CI, are you willing to contribute that?

**Comment by Uniminin** [comment]
@Kreyren you can add it yourself.

**Comment by Kreyren** [comment]
We also need CI to provide expected label.

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Kreyren** [comment]
```
choosenim-init: Downloading choosenim-0.6.0_linux_amd64
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: Forced Yes
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: No C compiler found. Nim compiler requires a C compiler.
        ... Install clang or gcc using your favourite package manager.
##[error]Process completed with exit code 1.
```

@Uniminin What package manager should we use?

**Comment by Kreyren** [comment]
@Uniminin Are different versions of said compiler a concern for the result of compilation?

**Comment by Kreyren** [comment]
@Uniminin Is there any sanitization required to ensure it's security?

**Comment by Uniminin** [comment]
> Are different versions of said compiler a concern for the result of compilation?
NO

**Comment by Uniminin** [comment]
Nim compiler requires a C compiler Of course

**Comment by Uniminin** [comment]
I would prefer to install nim from official package manager's user repos

**Comment by Kreyren** [comment]
> Nim compiler requires a C compiler Of course

So if it requires C compiler why is it not a concern? I would assume that we need to implement CI for various versions and distributions

**Comment by Kreyren** [comment]
> I would prefer to install nim from official package manager's user repos

Currently we are using debian:stable docker image in CI which does not seem to have Nim, what do you propose?

**Comment by Uniminin** [comment]
There are a number of other dependencies that you may need to install in order to use Nim. They Include:
* C Compiler. Either gcc or clang
* PCRE
* OpenSSL

**Comment by Uniminin** [comment]
nim is available for Debian and ubuntu. `apt-get install nim`

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Kreyren** [comment]
@Uniminin 

`nim check` returns:

```
 main.nim(5, 6) Hint: 'main.SoftwareVersion(major: float32, minor: float32, patch: float64)[declared in main.nim(5, 5)]' is declared but not used [XDeclaredButNotUsed]
main.nim(13, 6) Hint: 'main.programmingL(lang: string)[declared in main.nim(13, 5)]' is declared but not used [XDeclaredButNotUsed]
```

Please fix

**Comment by Kreyren** [comment]
Notice: This CI is too complicated to be processed efficiently on current GitHub CI -> Custom script is to be implemented to be fetched directly on the docker images

**Comment by Kreyren** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/RXT0112/Zernit/pullRequest?prid=5355411&bid=17546852)

**Comment by Uniminin** [comment]
Okay. I'll check it out tomorrow.

**Comment by Kreyren** [comment]
@Uniminin Status update?

I set up TODO list in OP feel free to claim their resolution else merging as stub implementation with new tracking.

**Pull request closed without merging**
